package it.polimi.automata.factories;

import it.polimi.automata.Transition;
import it.polimi.automata.labeling.Label;

import org.apache.commons.collections15.Factory;

/**
 * contains the factory that is used to create the transition of a Buchi
 * automaton or of an incomplete Buchi automaton
 * 
 * @author claudiomenghi
 * @param LABEL
 *            is the label of a transition
 * @param TRANSITION
 *            is the type of the transition to be generated by the factory
 */
public interface TransitionFactory<LABEL extends Label, TRANSITION extends Transition<LABEL>>
		extends Factory<TRANSITION> {

	/**
	 * creates a new transition with the empty label epsilon
	 * 
	 * @return a new transition labeled with the empty label epsilon
	 */
	public TRANSITION create();

	/**
	 * creates a new transition labeled with the specified condition
	 * 
	 * @param condition
	 *            is the condition that labels the transition
	 * @return a new transition labeled with the specified condition
	 * @throws NullPointerException
	 *             if the label is null
	 */
	public TRANSITION create(LABEL condition);

	/**
	 * creates a new transition with the specified condition and id
	 * 
	 * @param condition
	 *            is the condition that labels the transition
	 * @param id
	 *            is the id of the transition
	 * @return a new transition with the specified id and condition as label
	 * @throws NullPointerException
	 *             if the condition is null
	 * @throws IllegalArgumentException
	 *             if the id is not grater than or equal to zero
	 */
	public TRANSITION create(int id, LABEL condition);
}